name: Run Golden Master Regression Test 
on:
  push:
    branches:
    - "GoldenMaster"
  workflow_dispatch:
    inputs:
      generate_new_gold_master:
        description: 'Generate a new golden master for regression test'
        required: false
        default: false
        type: boolean

jobs:
  Run-Regression-Test:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest


