name: Run Generate Golden Master for Regression Test 
on:
  workflow_dispatch:
    inputs:
      generate_new_gold_master:
        description: 'Generate a new golden master for regression test'
        required: false
        default: false
        type: boolean

jobs:
  Run-Regression-Test:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell 
    permissions:
      contents: write
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Setup for test
      run: |
        $PSVersionTable
        ./SetUp.ps1
        Import-Module -Name ./PowerShell/ScubaGear

    - name: Run Regression Test
      run: ./Testing/Modules/RunFunctionalTests.ps1 -t Rego -p aad